[pytest]
pythonpath = .
base_url = http://127.0.0.1:8000
addopts = --headed --slowmo 500
          --output=evidence
          -vs --alluredir=./allure-results --clean-alluredir
# --alluredir: 指定存放"原始结果数据"的临时目录 (通常叫 allure-results)
# --clean-alluredir: 每次运行前清空该目录，防止历史数据干扰

# 让日志实时输出到控制台
log_cli = true
log_cli_level = INFO




